# -*- coding: utf-8 -*-
"""GENERADO por tools/gen_names.py desde PokeAPI - no editar a mano.

Nombres oficiales por idioma. FR y DE van en mayusculas y sin
acentos (fuente CP437, un byte por caracter); JA va en katakana
UTF-8 tal cual, porque se pinta con una fuente U8g2.
"""

LOCAL_NAMES = {
    1: {'fr': 'BULBIZARRE', 'de': 'BISASAM', 'ja': 'フシギダネ'},
    2: {'fr': 'HERBIZARRE', 'de': 'BISAKNOSP', 'ja': 'フシギソウ'},
    3: {'fr': 'FLORIZARRE', 'de': 'BISAFLOR', 'ja': 'フシギバナ'},
    4: {'fr': 'SALAMECHE', 'de': 'GLUMANDA', 'ja': 'ヒトカゲ'},
    5: {'fr': 'REPTINCEL', 'de': 'GLUTEXO', 'ja': 'リザード'},
    6: {'fr': 'DRACAUFEU', 'de': 'GLURAK', 'ja': 'リザードン'},
    7: {'fr': 'CARAPUCE', 'de': 'SCHIGGY', 'ja': 'ゼニガメ'},
    8: {'fr': 'CARABAFFE', 'de': 'SCHILLOK', 'ja': 'カメール'},
    9: {'fr': 'TORTANK', 'de': 'TURTOK', 'ja': 'カメックス'},
    10: {'fr': 'CHENIPAN', 'de': 'RAUPY', 'ja': 'キャタピー'},
    11: {'fr': 'CHRYSACIER', 'de': 'SAFCON', 'ja': 'トランセル'},
    12: {'fr': 'PAPILUSION', 'de': 'SMETTBO', 'ja': 'バタフリー'},
    13: {'fr': 'ASPICOT', 'de': 'HORNLIU', 'ja': 'ビードル'},
    14: {'fr': 'COCONFORT', 'de': 'KOKUNA', 'ja': 'コクーン'},
    15: {'fr': 'DARDARGNAN', 'de': 'BIBOR', 'ja': 'スピアー'},
    16: {'fr': 'ROUCOOL', 'de': 'TAUBSI', 'ja': 'ポッポ'},
    17: {'fr': 'ROUCOUPS', 'de': 'TAUBOGA', 'ja': 'ピジョン'},
    18: {'fr': 'ROUCARNAGE', 'de': 'TAUBOSS', 'ja': 'ピジョット'},
    19: {'de': 'RATTFRATZ', 'ja': 'コラッタ'},
    20: {'fr': 'RATTATAC', 'de': 'RATTIKARL', 'ja': 'ラッタ'},
    21: {'fr': 'PIAFABEC', 'de': 'HABITAK', 'ja': 'オニスズメ'},
    22: {'fr': 'RAPASDEPIC', 'de': 'IBITAK', 'ja': 'オニドリル'},
    23: {'fr': 'ABO', 'de': 'RETTAN', 'ja': 'アーボ'},
    24: {'ja': 'アーボック'},
    25: {'ja': 'ピカチュウ'},
    26: {'ja': 'ライチュウ'},
    27: {'fr': 'SABELETTE', 'de': 'SANDAN', 'ja': 'サンド'},
    28: {'fr': 'SABLAIREAU', 'de': 'SANDAMER', 'ja': 'サンドパン'},
    29: {'ja': 'ニドランF'},
    30: {'ja': 'ニドリーナ'},
    31: {'ja': 'ニドクイン'},
    32: {'ja': 'ニドランM'},
    33: {'ja': 'ニドリーノ'},
    34: {'ja': 'ニドキング'},
    35: {'fr': 'MELOFEE', 'de': 'PIEPI', 'ja': 'ピッピ'},
    36: {'fr': 'MELODELFE', 'de': 'PIXI', 'ja': 'ピクシー'},
    37: {'fr': 'GOUPIX', 'ja': 'ロコン'},
    38: {'fr': 'FEUNARD', 'de': 'VULNONA', 'ja': 'キュウコン'},
    39: {'fr': 'RONDOUDOU', 'de': 'PUMMELUFF', 'ja': 'プリン'},
    40: {'fr': 'GRODOUDOU', 'de': 'KNUDDELUFF', 'ja': 'プクリン'},
    41: {'fr': 'NOSFERAPTI', 'ja': 'ズバット'},
    42: {'fr': 'NOSFERALTO', 'ja': 'ゴルバット'},
    43: {'fr': 'MYSTHERBE', 'de': 'MYRAPLA', 'ja': 'ナゾノクサ'},
    44: {'fr': 'ORTIDE', 'de': 'DUFLOR', 'ja': 'クサイハナ'},
    45: {'fr': 'RAFFLESIA', 'de': 'GIFLOR', 'ja': 'ラフレシア'},
    46: {'ja': 'パラス'},
    47: {'de': 'PARASEK', 'ja': 'パラセクト'},
    48: {'fr': 'MIMITOSS', 'de': 'BLUZUK', 'ja': 'コンパン'},
    49: {'fr': 'AEROMITE', 'de': 'OMOT', 'ja': 'モルフォン'},
    50: {'fr': 'TAUPIQUEUR', 'de': 'DIGDA', 'ja': 'ディグダ'},
    51: {'fr': 'TRIOPIKEUR', 'de': 'DIGDRI', 'ja': 'ダグトリオ'},
    52: {'fr': 'MIAOUSS', 'de': 'MAUZI', 'ja': 'ニャース'},
    53: {'de': 'SNOBILIKAT', 'ja': 'ペルシアン'},
    54: {'fr': 'PSYKOKWAK', 'de': 'ENTON', 'ja': 'コダック'},
    55: {'fr': 'AKWAKWAK', 'de': 'ENTORON', 'ja': 'ゴルダック'},
    56: {'fr': 'FEROSINGE', 'de': 'MENKI', 'ja': 'マンキー'},
    57: {'fr': 'COLOSSINGE', 'de': 'RASAFF', 'ja': 'オコリザル'},
    58: {'fr': 'CANINOS', 'de': 'FUKANO', 'ja': 'ガーディ'},
    59: {'fr': 'ARCANIN', 'de': 'ARKANI', 'ja': 'ウインディ'},
    60: {'fr': 'PTITARD', 'de': 'QUAPSEL', 'ja': 'ニョロモ'},
    61: {'fr': 'TETARTE', 'de': 'QUAPUTZI', 'ja': 'ニョロゾ'},
    62: {'fr': 'TARTARD', 'de': 'QUAPPO', 'ja': 'ニョロボン'},
    63: {'ja': 'ケーシィ'},
    64: {'ja': 'ユンゲラー'},
    65: {'de': 'SIMSALA', 'ja': 'フーディン'},
    66: {'fr': 'MACHOC', 'de': 'MACHOLLO', 'ja': 'ワンリキー'},
    67: {'fr': 'MACHOPEUR', 'de': 'MASCHOCK', 'ja': 'ゴーリキー'},
    68: {'fr': 'MACKOGNEUR', 'de': 'MACHOMEI', 'ja': 'カイリキー'},
    69: {'fr': 'CHETIFLOR', 'de': 'KNOFENSA', 'ja': 'マダツボミ'},
    70: {'fr': 'BOUSTIFLOR', 'de': 'ULTRIGARIA', 'ja': 'ウツドン'},
    71: {'fr': 'EMPIFLOR', 'de': 'SARZENIA', 'ja': 'ウツボット'},
    72: {'de': 'TENTACHA', 'ja': 'メノクラゲ'},
    73: {'de': 'TENTOXA', 'ja': 'ドククラゲ'},
    74: {'fr': 'RACAILLOU', 'de': 'KLEINSTEIN', 'ja': 'イシツブテ'},
    75: {'fr': 'GRAVALANCH', 'de': 'GEOROK', 'ja': 'ゴローン'},
    76: {'fr': 'GROLEM', 'de': 'GEOWAZ', 'ja': 'ゴローニャ'},
    77: {'de': 'PONITA', 'ja': 'ポニータ'},
    78: {'fr': 'GALOPA', 'de': 'GALLOPA', 'ja': 'ギャロップ'},
    79: {'fr': 'RAMOLOSS', 'de': 'FLEGMON', 'ja': 'ヤドン'},
    80: {'fr': 'FLAGADOSS', 'de': 'LAHMUS', 'ja': 'ヤドラン'},
    81: {'fr': 'MAGNETI', 'de': 'MAGNETILO', 'ja': 'コイル'},
    82: {'ja': 'レアコイル'},
    83: {'fr': 'CANARTICHO', 'de': 'PORENTA', 'ja': 'カモネギ'},
    84: {'de': 'DODU', 'ja': 'ドードー'},
    85: {'de': 'DODRI', 'ja': 'ドードリオ'},
    86: {'fr': 'OTARIA', 'de': 'JUROB', 'ja': 'パウワウ'},
    87: {'fr': 'LAMANTINE', 'de': 'JUGONG', 'ja': 'ジュゴン'},
    88: {'fr': 'TADMORV', 'de': 'SLEIMA', 'ja': 'ベトベター'},
    89: {'fr': 'GROTADMORV', 'de': 'SLEIMOK', 'ja': 'ベトベトン'},
    90: {'fr': 'KOKIYAS', 'de': 'MUSCHAS', 'ja': 'シェルダー'},
    91: {'fr': 'CRUSTABRI', 'de': 'AUSTOS', 'ja': 'パルシェン'},
    92: {'fr': 'FANTOMINUS', 'de': 'NEBULAK', 'ja': 'ゴース'},
    93: {'fr': 'SPECTRUM', 'de': 'ALPOLLO', 'ja': 'ゴースト'},
    94: {'fr': 'ECTOPLASMA', 'ja': 'ゲンガー'},
    95: {'ja': 'イワーク'},
    96: {'fr': 'SOPORIFIK', 'de': 'TRAUMATO', 'ja': 'スリープ'},
    97: {'fr': 'HYPNOMADE', 'ja': 'スリーパー'},
    98: {'ja': 'クラブ'},
    99: {'fr': 'KRABBOSS', 'ja': 'キングラー'},
    100: {'fr': 'VOLTORBE', 'de': 'VOLTOBAL', 'ja': 'ビリリダマ'},
    101: {'de': 'LEKTROBAL', 'ja': 'マルマイン'},
    102: {'fr': 'NOEUNOEUF', 'de': 'OWEI', 'ja': 'タマタマ'},
    103: {'fr': 'NOADKOKO', 'de': 'KOKOWEI', 'ja': 'ナッシー'},
    104: {'fr': 'OSSELAIT', 'de': 'TRAGOSSO', 'ja': 'カラカラ'},
    105: {'fr': 'OSSATUEUR', 'de': 'KNOGGA', 'ja': 'ガラガラ'},
    106: {'fr': 'KICKLEE', 'de': 'KICKLEE', 'ja': 'サワムラー'},
    107: {'fr': 'TYGNON', 'de': 'NOCKCHAN', 'ja': 'エビワラー'},
    108: {'fr': 'EXCELANGUE', 'de': 'SCHLURP', 'ja': 'ベロリンガ'},
    109: {'fr': 'SMOGO', 'de': 'SMOGON', 'ja': 'ドガース'},
    110: {'fr': 'SMOGOGO', 'de': 'SMOGMOG', 'ja': 'マタドガス'},
    111: {'fr': 'RHINOCORNE', 'de': 'RIHORN', 'ja': 'サイホーン'},
    112: {'fr': 'RHINOFEROS', 'de': 'RIZEROS', 'ja': 'サイドン'},
    113: {'fr': 'LEVEINARD', 'de': 'CHANEIRA', 'ja': 'ラッキー'},
    114: {'fr': 'SAQUEDENEU', 'ja': 'モンジャラ'},
    115: {'fr': 'KANGOUREX', 'de': 'KANGAMA', 'ja': 'ガルーラ'},
    116: {'fr': 'HYPOTREMPE', 'de': 'SEEPER', 'ja': 'タッツー'},
    117: {'fr': 'HYPOCEAN', 'de': 'SEEMON', 'ja': 'シードラ'},
    118: {'fr': 'POISSIRENE', 'de': 'GOLDINI', 'ja': 'トサキント'},
    119: {'fr': 'POISSOROY', 'de': 'GOLKING', 'ja': 'アズマオウ'},
    120: {'fr': 'STARI', 'de': 'STERNDU', 'ja': 'ヒトデマン'},
    121: {'fr': 'STAROSS', 'ja': 'スターミー'},
    122: {'fr': 'M. MIME', 'de': 'PANTIMOS', 'ja': 'バリヤード'},
    123: {'fr': 'INSECATEUR', 'de': 'SICHLOR', 'ja': 'ストライク'},
    124: {'fr': 'LIPPOUTOU', 'de': 'ROSSANA', 'ja': 'ルージュラ'},
    125: {'fr': 'ELEKTEK', 'de': 'ELEKTEK', 'ja': 'エレブー'},
    126: {'ja': 'ブーバー'},
    127: {'fr': 'SCARABRUTE', 'ja': 'カイロス'},
    128: {'ja': 'ケンタロス'},
    129: {'fr': 'MAGICARPE', 'de': 'KARPADOR', 'ja': 'コイキング'},
    130: {'fr': 'LEVIATOR', 'de': 'GARADOS', 'ja': 'ギャラドス'},
    131: {'fr': 'LOKHLASS', 'ja': 'ラプラス'},
    132: {'fr': 'METAMORPH', 'ja': 'メタモン'},
    133: {'fr': 'EVOLI', 'de': 'EVOLI', 'ja': 'イーブイ'},
    134: {'fr': 'AQUALI', 'de': 'AQUANA', 'ja': 'シャワーズ'},
    135: {'fr': 'VOLTALI', 'de': 'BLITZA', 'ja': 'サンダース'},
    136: {'fr': 'PYROLI', 'de': 'FLAMARA', 'ja': 'ブースター'},
    137: {'ja': 'ポリゴン'},
    138: {'fr': 'AMONITA', 'de': 'AMONITAS', 'ja': 'オムナイト'},
    139: {'fr': 'AMONISTAR', 'de': 'AMOROSO', 'ja': 'オムスター'},
    140: {'ja': 'カブト'},
    141: {'ja': 'カブトプス'},
    142: {'fr': 'PTERA', 'ja': 'プテラ'},
    143: {'fr': 'RONFLEX', 'de': 'RELAXO', 'ja': 'カビゴン'},
    144: {'fr': 'ARTIKODIN', 'de': 'ARKTOS', 'ja': 'フリーザー'},
    145: {'fr': 'ELECTHOR', 'ja': 'サンダー'},
    146: {'fr': 'SULFURA', 'de': 'LAVADOS', 'ja': 'ファイヤー'},
    147: {'fr': 'MINIDRACO', 'ja': 'ミニリュウ'},
    148: {'fr': 'DRACO', 'de': 'DRAGONIR', 'ja': 'ハクリュー'},
    149: {'fr': 'DRACOLOSSE', 'de': 'DRAGORAN', 'ja': 'カイリュー'},
    150: {'de': 'MEWTU', 'ja': 'ミュウツー'},
    151: {'ja': 'ミュウ'},
}
